import type { NextPage } from "next";
import dynamic from "next/dynamic";
import Head from "next/head";
import { useRouter } from "next/router";
import Banner from "../components/Banner";
import Content from "../components/Content";
import Footer from "../components/Footer";
import Header from "../components/Header";
import Logged from "../components/Logged";
import Notlogged from "../components/Notlogged";
dynamic(import("tw-elements"), { ssr: false });
import verifyLogin from "../components/verifyLogin";

const Description: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {verifyLogin() == true ? (
        <Header marginprop="m-5">
          <Logged />
        </Header>
      ) : (
        <Header marginprop="ml-5">
          <Notlogged />
        </Header>
      )}
      <Banner />
      <Content />
      <p>{useRouter().query.id}</p>
    </>
  );
};

export default Description;
