import axios from "axios";
import type { NextPage } from "next";
import dynamic from "next/dynamic";
import Head from "next/head";
dynamic(import("tw-elements"), { ssr: false });
import Link from "next/link";
import { useRouter } from "next/router";
import { parseCookies } from "nookies";
import { useEffect, useState } from "react";
import Banner from "../components/Banner";
import Footer from "../components/Footer";
import Header from "../components/Header";
import Logged from "../components/Logged";
import Notlogged from "../components/Notlogged";
import styles from "../styles/Description.module.css";

const Description: NextPage = () => {
  const router = useRouter();
  const query: any = router.query;

  let [request_response, setUrl] = useState([]);

  async function getApi() {
    try {
      const response = await axios.get("https://fakestoreapi.com/products?");
      setUrl(response.data);
    } catch (error) {
      console.log(error);
    }
  }

  const cookies = parseCookies();

  let [cookiestate, setcookiestate] = useState("");

  useEffect(() => {
    if (router.isReady) {
      setcookiestate(cookies.islogged);
      getApi();
    }
  }, [router, cookiestate]);

  let index: number = ~~query.id - 1;
  let product_details: any = request_response[index];

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {cookiestate == "true" ? (
        <Header marginprop="m-5">
          <Logged />
        </Header>
      ) : (
        <Header marginprop="ml-5">
          <Notlogged />
        </Header>
      )}
      <Banner />
      <div className={styles["product-card"]}>
        <img src={product_details?.image} alt="" />
        <div>
          <p>{product_details?.title}</p>
          <p>{product_details?.description}</p>
          <div className={styles["pricebuy-box"]}>
            <p>R${product_details?.price}</p>
            <a
              className={`btn btn-active btn-success ${styles.ssbutton}`}
              href="#"
            >
              Comprar Agora
            </a>
            <Link href={"/"}>
              <a
                className={`btn btn-active btn-info ${styles.smbutton}`}
                href=""
              >
                Voltar
              </a>
            </Link>
          </div>
        </div>
      </div>
      <Footer />
    </>
  );
};

export default Description;
